In [ ]:
##        ASSIGNMENT 1: DATA CLEANING AND SUMMARISING       ##
##                   STUDENT NAME : SURAJ KANNAN
##                       STUDENT ID: S3668855

In [2]:
#IMPORTING PANDAS AND NUMPY 
import pandas as pd
import numpy as np

In [3]:
## LOADING THE BANK.CSV FILE
bank_var1='D:\Downloads\\Bank.csv'
bank=pd.read_csv(bank_var1, sep=';', decimal='.', header=0)

In [4]:
#DISPLAYING THE DATA TYPES OF THE COLUMNS
bank.dtypes

age               float64
job                object
marital            object
education          object
default            object
housing            object
loan               object
contact            object
month              object
day_of_week        object
duration          float64
campaign          float64
pdays              object
previous           object
poutcome           object
emp.var.rate       object
cons.price.idx    float64
cons.conf.idx     float64
euribor3m          object
nr.employed        object
y                  object
dtype: object

In [5]:
#DISPLAYING THE COLUMN NAMES 
bank.columns

Index([u'age', u'job', u'marital', u'education', u'default', u'housing',
       u'loan', u'contact', u'month', u'day_of_week', u'duration', u'campaign',
       u'pdays', u'previous', u'poutcome', u'emp.var.rate', u'cons.price.idx',
       u'cons.conf.idx', u'euribor3m', u'nr.employed', u'y'],
      dtype='object')

In [6]:
##CONVERTING THE DATA TYPE OF 'PDAYS' TO NUMERIC
bank['pdays'] = bank['pdays'].convert_objects(convert_numeric=True)

C:\Users\jayar\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use Series.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  """Entry point for launching an IPython kernel.


In [7]:
##CONVERTING THE DATA TYPE OF 'previous' TO NUMERIC
bank['previous'] = bank['previous'].convert_objects(convert_numeric=True)

C:\Users\jayar\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use Series.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  """Entry point for launching an IPython kernel.


In [8]:
##CONVERTING THE DATA TYPE OF 'emp.var.rate' TO NUMERIC
bank['emp.var.rate'] = bank['emp.var.rate'].convert_objects(convert_numeric=True)

C:\Users\jayar\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use Series.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  """Entry point for launching an IPython kernel.


In [9]:
##CONVERTING THE DATA TYPE OF 'euribor3m' TO NUMERIC
bank['euribor3m'] = bank['euribor3m'].convert_objects(convert_numeric=True)

C:\Users\jayar\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use Series.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  """Entry point for launching an IPython kernel.


In [10]:
##CONVERTING THE DATA TYPE OF 'nr.employed' TO NUMERIC
bank['nr.employed'] = bank['nr.employed'].convert_objects(convert_numeric=True)

C:\Users\jayar\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use Series.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  """Entry point for launching an IPython kernel.


In [11]:
#DISPLAYING BANK DATA TYPES
bank.dtypes

age               float64
job                object
marital            object
education          object
default            object
housing            object
loan               object
contact            object
month              object
day_of_week        object
duration          float64
campaign          float64
pdays             float64
previous          float64
poutcome           object
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
y                  object
dtype: object

In [12]:
#DISPLAYING UNIQUE VALUES
bank.job.unique()

array(['blue-collar', 'services', 'admin.', 'entrepreneur',
       'self-employed', 'technician', 'management', 'student', 'retired',
       'housemaid', 'unemployed', 'unknown'], dtype=object)

In [13]:
#REPLACING THE TYPO 
bank.job.replace('admin.', 'admin', inplace=True)

In [14]:
#DISPLAYING UNIQUE VALUES
bank.job.unique()

array(['blue-collar', 'services', 'admin', 'entrepreneur',
       'self-employed', 'technician', 'management', 'student', 'retired',
       'housemaid', 'unemployed', 'unknown'], dtype=object)

In [15]:
#DISPLAYING UNIQUE VALUES
bank.marital.unique()

array(['married', 'single', 'divorced', 'unknown',
       'divorceded\xe2\x80\x9d;\xe2\x80\x9dbasic.9y'], dtype=object)

In [16]:
#DISPLAYING TOTAL COUNT
bank.marital.count()

4119

In [17]:
#DISPLAYING COUNT IF EACH ARGUMENT
bank['marital'].value_counts()

married                  2509
single                   1153
divorced                  445
unknown                    11
divorceded”;”basic.9y       1
Name: marital, dtype: int64

In [18]:
#LOCATING THE VALUE
np.where(bank.marital=="divorceded\xe2\x80\x9d;\xe2\x80\x9dbasic.9y")

(array([650], dtype=int64),)

In [19]:
#DISPLAYING THE VALUES OF THE ATTRIBUTE
bank.loc[650]

age                                  41
job                         blue-collar
marital           divorceded”;”basic.9y
education                            no
default                             yes
housing                              no
loan                           cellular
contact                             may
month                               thu
day_of_week                         102
duration                              1
campaign                            999
pdays                                 0
previous                            NaN
poutcome                           -1.8
emp.var.rate                     92.893
cons.price.idx                    -46.2
cons.conf.idx                     1.327
euribor3m                        5099.1
nr.employed                         NaN
y                                   NaN
Name: 650, dtype: object

In [20]:
#CREATING A SEBSET 
a=bank.ix[650,3:21]

C:\Users\jayar\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


In [21]:
#DISPLAYING THE SUBSET
a

education               no
default                yes
housing                 no
loan              cellular
contact                may
month                  thu
day_of_week            102
duration                 1
campaign               999
pdays                    0
previous               NaN
poutcome              -1.8
emp.var.rate        92.893
cons.price.idx       -46.2
cons.conf.idx        1.327
euribor3m           5099.1
nr.employed            NaN
y                      NaN
Name: 650, dtype: object

In [22]:
#SHIFTING THE AXIS BY ONE ENTRTY
a=a.shift(1,axis=0)

In [23]:
#ASSIGNING A VALUE MANUALLY
a.education="basic.9y"

In [24]:
a

education         basic.9y
default                 no
housing                yes
loan                    no
contact           cellular
month                  may
day_of_week            thu
duration               102
campaign                 1
pdays                  999
previous                 0
poutcome               NaN
emp.var.rate          -1.8
cons.price.idx      92.893
cons.conf.idx        -46.2
euribor3m            1.327
nr.employed         5099.1
y                      NaN
Name: 650, dtype: object

In [25]:
#CREATING A SUBSET
bank.ix[650,3:21]=a

In [26]:
#REPLACING THE TYPO WITH THE CORRECT VALUE
bank['marital'].replace('divorceded\xe2\x80\x9d;\xe2\x80\x9dbasic.9y', 'divorced', inplace=True)

In [27]:
#COUNTING THE NUMBER OF VALUES IN MARITAL ATTRIBUTE
bank['marital'].value_counts()

married     2509
single      1153
divorced     446
unknown       11
Name: marital, dtype: int64

In [28]:
#DISPLAYING THE VALIUE IN THE LOACTION 
bank.loc[650]

age                        41
job               blue-collar
marital              divorced
education            basic.9y
default                    no
housing                   yes
loan                       no
contact              cellular
month                     may
day_of_week               thu
duration                  102
campaign                    1
pdays                     999
previous                    0
poutcome                  NaN
emp.var.rate             -1.8
cons.price.idx         92.893
cons.conf.idx           -46.2
euribor3m               1.327
nr.employed            5099.1
y                         NaN
Name: 650, dtype: object

In [29]:
#DISPLAYING UNIQUE VALUES
bank.education.unique()

array(['basic.9y', 'high.school', 'university.degree',
       'professional.course', 'basic.6y', 'basic.4y', 'unknown',
       'basic.6yes\xe2\x80\x9d;\xe2\x80\x9dno', 'illiterate'],
      dtype=object)

In [30]:
#LOCATING THE "NAN" VALUE
np.where(bank.education=="basic.6yes\xe2\x80\x9d;\xe2\x80\x9dno")

(array([574], dtype=int64),)

In [31]:
#DISPLAYING THE VALUES IN THE LOCATION
bank.loc[574]

age                            47
job                   blue-collar
marital                   married
education         basic.6yes”;”no
default                yess”;”yes
housing                  cellular
loan                          jul
contact                       mon
month                         298
day_of_week                     3
duration                      999
campaign                        0
pdays                         NaN
previous                      1.4
poutcome                   93.918
emp.var.rate                -42.7
cons.price.idx              4.962
cons.conf.idx              5228.1
euribor3m                     NaN
nr.employed                   NaN
y                             NaN
Name: 574, dtype: object

In [32]:
# CREATING A SUBSET B
b=bank.ix[574,5:21]

In [33]:
#DISPLAYING B
b

housing           cellular
loan                   jul
contact                mon
month                  298
day_of_week              3
duration               999
campaign                 0
pdays                  NaN
previous               1.4
poutcome            93.918
emp.var.rate         -42.7
cons.price.idx       4.962
cons.conf.idx       5228.1
euribor3m              NaN
nr.employed            NaN
y                      NaN
Name: 574, dtype: object

In [34]:
#SHIFTING THE AXIS OF THE ENTRIES IN B
b=b.shift(2,axis=0)

In [35]:
#DISPLAYINHG THE B
b

housing                NaN
loan                   NaN
contact           cellular
month                  jul
day_of_week            mon
duration               298
campaign                 3
pdays                  999
previous                 0
poutcome               NaN
emp.var.rate           1.4
cons.price.idx      93.918
cons.conf.idx        -42.7
euribor3m            4.962
nr.employed         5228.1
y                      NaN
Name: 574, dtype: object

In [36]:
#ASSIGNING THE VALUES MANUALLY
b.housing="yes"
b.loan="yes"

In [37]:
bank.ix[574,5:21]=b

In [38]:
bank.loc[574]

age                            47
job                   blue-collar
marital                   married
education         basic.6yes”;”no
default                yess”;”yes
housing                       yes
loan                          yes
contact                  cellular
month                         jul
day_of_week                   mon
duration                      298
campaign                        3
pdays                         999
previous                        0
poutcome                      NaN
emp.var.rate                  1.4
cons.price.idx             93.918
cons.conf.idx               -42.7
euribor3m                   4.962
nr.employed                5228.1
y                             NaN
Name: 574, dtype: object

In [39]:
b=bank.ix[574].copy()
b


age                            47
job                   blue-collar
marital                   married
education         basic.6yes”;”no
default                yess”;”yes
housing                       yes
loan                          yes
contact                  cellular
month                         jul
day_of_week                   mon
duration                      298
campaign                        3
pdays                         999
previous                        0
poutcome                      NaN
emp.var.rate                  1.4
cons.price.idx             93.918
cons.conf.idx               -42.7
euribor3m                   4.962
nr.employed                5228.1
y                             NaN
Name: 574, dtype: object

In [40]:
b.education="basic.6y"
b.default="no"
b.campaign=3

In [41]:
bank.loc[574]=b

In [42]:
bank.loc[574]

age                        47
job               blue-collar
marital               married
education            basic.6y
default                    no
housing                   yes
loan                      yes
contact              cellular
month                     jul
day_of_week               mon
duration                  298
campaign                    3
pdays                     999
previous                    0
poutcome                  NaN
emp.var.rate              1.4
cons.price.idx         93.918
cons.conf.idx           -42.7
euribor3m               4.962
nr.employed            5228.1
y                         NaN
Name: 574, dtype: object

In [43]:
bank.education.unique()

array(['basic.9y', 'high.school', 'university.degree',
       'professional.course', 'basic.6y', 'basic.4y', 'unknown',
       'illiterate'], dtype=object)

In [44]:
bank.default.unique()

array(['no', 'unknown', 'noo\xe2\x80\x9d;\xe2\x80\x9dyes', 'yes'],
      dtype=object)

In [45]:
np.where(bank.default=="noo\xe2\x80\x9d;\xe2\x80\x9dyes")

(array([569], dtype=int64),)

In [46]:
bank.loc[569]

age                              33
job                           admin
marital                      single
education         university.degree
default                   noo”;”yes
housing                         yes
loan                       cellular
contact                         aug
month                           tue
day_of_week                     275
duration                          6
campaign                        999
pdays                             0
previous                        NaN
poutcome                        1.4
emp.var.rate                 93.444
cons.price.idx                -36.1
cons.conf.idx                 4.963
euribor3m                    5228.1
nr.employed                     NaN
y                               NaN
Name: 569, dtype: object

In [47]:
c=bank.ix[569,4:21]

In [48]:
c

default           noo”;”yes
housing                 yes
loan               cellular
contact                 aug
month                   tue
day_of_week             275
duration                  6
campaign                999
pdays                     0
previous                NaN
poutcome                1.4
emp.var.rate         93.444
cons.price.idx        -36.1
cons.conf.idx         4.963
euribor3m            5228.1
nr.employed             NaN
y                       NaN
Name: 569, dtype: object

In [49]:
c=c.shift(1,axis=0)

In [50]:
c

default                 NaN
housing           noo”;”yes
loan                    yes
contact            cellular
month                   aug
day_of_week             tue
duration                275
campaign                  6
pdays                   999
previous                  0
poutcome                NaN
emp.var.rate            1.4
cons.price.idx       93.444
cons.conf.idx         -36.1
euribor3m             4.963
nr.employed          5228.1
y                       NaN
Name: 569, dtype: object

In [51]:
c.default='no'
c.housing='yes'

In [52]:
c

default                 no
housing                yes
loan                   yes
contact           cellular
month                  aug
day_of_week            tue
duration               275
campaign                 6
pdays                  999
previous                 0
poutcome               NaN
emp.var.rate           1.4
cons.price.idx      93.444
cons.conf.idx        -36.1
euribor3m            4.963
nr.employed         5228.1
y                      NaN
Name: 569, dtype: object

In [53]:
bank.ix[569,4:21]=c

In [54]:
bank.loc[569]

age                              33
job                           admin
marital                      single
education         university.degree
default                          no
housing                         yes
loan                            yes
contact                    cellular
month                           aug
day_of_week                     tue
duration                        275
campaign                          6
pdays                           999
previous                          0
poutcome                        NaN
emp.var.rate                    1.4
cons.price.idx               93.444
cons.conf.idx                 -36.1
euribor3m                     4.963
nr.employed                  5228.1
y                               NaN
Name: 569, dtype: object

In [55]:
bank.housing.unique()

array(['yes', 'no', 'unknown'], dtype=object)

In [56]:
bank.loan.unique()

array(['no', 'unknown', 'yes'], dtype=object)

In [57]:
bank.contact.unique()

array(['cellular', 'telephone'], dtype=object)

In [58]:
bank.month.unique()

array(['may', 'jun', 'nov', 'sep', 'jul', 'aug', 'mar', 'oct', 'apr',
       'dec'], dtype=object)

In [59]:
bank.day_of_week.unique()

array(['fri', 'wed', 'mon', 'thu', 'tue',
       'thu\xe2\x80\x9d;-;1;999;0;nonexistent"'], dtype=object)

In [60]:
np.where(bank.day_of_week=='thu\xe2\x80\x9d;-;1;999;0;nonexistent"')

(array([678], dtype=int64),)

In [61]:
bank.loc[678]

age                                        39
job                               blue-collar
marital                               married
education                            basic.6y
default                                    no
housing                                    no
loan                                       no
contact                             telephone
month                                     may
day_of_week       thu”;-;1;999;0;nonexistent"
duration                                  1.1
campaign                               93.994
pdays                                   -36.4
previous                                4.855
poutcome                                 5191
emp.var.rate                              NaN
cons.price.idx                            NaN
cons.conf.idx                             NaN
euribor3m                                 NaN
nr.employed                               NaN
y                                         NaN
Name: 678, dtype: object

In [62]:
d=bank.ix[678,10:21]

In [63]:
d

duration             1.1
campaign          93.994
pdays              -36.4
previous           4.855
poutcome            5191
emp.var.rate         NaN
cons.price.idx       NaN
cons.conf.idx        NaN
euribor3m            NaN
nr.employed          NaN
y                    NaN
Name: 678, dtype: object

In [64]:
d=d.shift(6,axis=0)

In [65]:
d

duration             NaN
campaign             NaN
pdays                NaN
previous             NaN
poutcome             NaN
emp.var.rate         NaN
cons.price.idx       1.1
cons.conf.idx     93.994
euribor3m          -36.4
nr.employed        4.855
y                   5191
Name: 678, dtype: object

In [66]:

d.dutation='-'
d.campaign=1
d.pdays=999
d.previous=0
d.poutcome='nonexistent'
d.y='yes'

In [67]:
bank.ix[678,10:21]=d

In [68]:
dd=bank.ix[678,10:21]

In [69]:
bank.loc[678]

age                                        39
job                               blue-collar
marital                               married
education                            basic.6y
default                                    no
housing                                    no
loan                                       no
contact                             telephone
month                                     may
day_of_week       thu”;-;1;999;0;nonexistent"
duration                                  NaN
campaign                                    1
pdays                                     999
previous                                    0
poutcome                          nonexistent
emp.var.rate                              NaN
cons.price.idx                            1.1
cons.conf.idx                          93.994
euribor3m                               -36.4
nr.employed                             4.855
y                                         yes
Name: 678, dtype: object

In [70]:
d=bank.ix[678,9:21]

In [71]:
d

day_of_week       thu”;-;1;999;0;nonexistent"
duration                                  NaN
campaign                                    1
pdays                                     999
previous                                    0
poutcome                          nonexistent
emp.var.rate                              NaN
cons.price.idx                            1.1
cons.conf.idx                          93.994
euribor3m                               -36.4
nr.employed                             4.855
y                                         yes
Name: 678, dtype: object

In [72]:
d.day_of_week='thu'

In [73]:
bank.ix[678,9:21]=d

In [74]:
bank.loc[678]

age                        39
job               blue-collar
marital               married
education            basic.6y
default                    no
housing                    no
loan                       no
contact             telephone
month                     may
day_of_week               thu
duration                  NaN
campaign                    1
pdays                     999
previous                    0
poutcome          nonexistent
emp.var.rate              NaN
cons.price.idx            1.1
cons.conf.idx          93.994
euribor3m               -36.4
nr.employed             4.855
y                         yes
Name: 678, dtype: object

In [75]:
bank.day_of_week.unique()

array(['fri', 'wed', 'mon', 'thu', 'tue'], dtype=object)

In [76]:
bank.duration.unique()

array([487.0, 346.0, 227.0, 17.0, 58.0, 128.0, 290.0, 44.0, 68.0, 170.0,
       301.0, 148.0, 97.0, 211.0, 553.0, 698.0, 191.0, 59.0, 38.0, 849.0,
       326.0, 222.0, 626.0, 119.0, 388.0, 479.0, 446.0, 127.0, 109.0,
       113.0, 393.0, 151.0, 256.0, 42.0, 525.0, 57.0, 499.0, 84.0, 137.0,
       31.0, 430.0, 126.0, 340.0, 412.0, 132.0, 79.0, 341.0, 157.0, 252.0,
       263.0, 215.0, 89.0, 143.0, 40.0, 10.0, 481.0, 233.0, 204.0, 403.0,
       180.0, 16.0, 447.0, 81.0, 361.0, 1091.0, 395.0, 432.0, 596.0, 77.0,
       768.0, 96.0, 357.0, 459.0, 11.0, 264.0, 93.0, 374.0, 158.0, 95.0,
       835.0, 505.0, 300.0, 390.0, 274.0, 135.0, 257.0, 268.0, 477.0,
       91.0, 76.0, 103.0, 436.0, 483.0, 250.0, 259.0, 389.0, 7.0, 123.0,
       92.0, 297.0, 406.0, 104.0, 854.0, 147.0, 203.0, 149.0, 144.0,
       394.0, 523.0, 73.0, 197.0, 108.0, 80.0, 114.0, 122.0, 1161.0,
       181.0, 239.0, 360.0, 314.0, 984.0, 663.0, 141.0, 706.0, 797.0,
       311.0, 63.0, 111.0, 49.0, 171.0, 242.0, 279.0, 246.0, 

In [77]:
bank['pdays'] = bank['pdays'].convert_objects(convert_numeric=True)

C:\Users\jayar\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use Series.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  """Entry point for launching an IPython kernel.


In [78]:
bank['duration'] = bank['duration'].convert_objects(convert_numeric=True)

C:\Users\jayar\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use Series.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  """Entry point for launching an IPython kernel.


In [79]:
bank['duration'].fillna(bank['duration'].mean(axis=0),inplace=True)

In [80]:
bank['campaign'] = bank['campaign'].convert_objects(convert_numeric=True)

C:\Users\jayar\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use Series.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  """Entry point for launching an IPython kernel.


In [81]:
bank['emp.var.rate'] = bank['emp.var.rate'].convert_objects(convert_numeric=True)

C:\Users\jayar\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use Series.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  """Entry point for launching an IPython kernel.


In [82]:
bank.campaign.unique()

array([ 2.,  4.,  1.,  3.,  6.,  7., 27.,  5., 12., 14., 10.,  8., 11.,
       13.,  9., 15., 16., 18., 17., 22., 19., 23., 24., 35., 29.])

In [83]:
bank.pdays.unique()

array([999.,  12.,   3.,   6.,   5.,   2.,  10.,  11.,   7.,   1.,  18.,
         4.,  15.,   0.,  16.,   9.,  19.,  17.,  13.,  21.,  14.])

In [84]:
bank.previous.unique()

array([0., 2., 1., 3., 5., 4., 6.])

In [85]:
bank.poutcome.unique()

array(['nonexistent', 'failure', 'success', nan], dtype=object)

In [86]:
bank_columns=bank.columns[12:20]

In [87]:
bank_columns

Index([u'pdays', u'previous', u'poutcome', u'emp.var.rate', u'cons.price.idx',
       u'cons.conf.idx', u'euribor3m', u'nr.employed'],
      dtype='object')

In [88]:
for i in list(bank_columns):
    print(i)
    print(bank[i].unique())

pdays
[999.  12.   3.   6.   5.   2.  10.  11.   7.   1.  18.   4.  15.   0.
  16.   9.  19.  17.  13.  21.  14.]
previous
[0. 2. 1. 3. 5. 4. 6.]
poutcome
['nonexistent' 'failure' 'success' nan]
emp.var.rate
[-1.8  1.1  1.4 -0.1 -1.1 -2.9 -1.7 -3.4  nan -3.  -0.2]
cons.price.idx
[92.89299999999999 93.994 94.465 93.2 94.199 93.91799999999999 93.444
 93.369 92.84299999999999 92.963 94.601 94.027 92.37899999999999 92.431
 93.749 93.075 nan 94.055 92.469 94.76700000000001 92.20100000000001
 92.649 94.215 93.876 93.79799999999999 '93.918' 1.1 92.713 92.756]
cons.conf.idx
[-46.2   -36.4   -41.8   -42.    -37.5   -42.7   -36.1   -34.8   -50.
 -40.8   -49.5   -38.3   -29.8   -26.9   -34.6   -47.1   -39.8   -33.6
 -50.8   -31.4   -30.1   -40.3   -40.    -40.4    93.994 -33.    -45.9  ]
euribor3m
[  1.313   4.855   4.962   4.959   4.191   0.884   0.879   4.153   4.958
   4.968   4.859   4.963   4.957   4.965   4.961   0.639   4.967   4.864
   4.856   1.299   4.86    1.687   4.865   1.268   4.12 

In [89]:
bank['cons.price.idx'] = bank['cons.price.idx'].convert_objects(convert_numeric=True)

C:\Users\jayar\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use Series.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  """Entry point for launching an IPython kernel.


In [90]:
bank['cons.price.idx']

0       92.893
1       93.994
2       94.465
3       94.465
4       93.200
5       94.199
6       94.199
7       93.200
8       93.200
9       93.994
10      93.918
11      93.918
12      93.994
13      94.465
14      92.893
15      93.918
16      93.918
17      93.918
18      93.444
19      93.918
20      93.918
21      93.369
22      93.444
23      93.444
24      93.994
25      93.444
26      93.994
27      92.893
28      93.994
29      93.444
         ...  
4089    92.431
4090    93.994
4091    93.994
4092    93.918
4093    93.918
4094    92.649
4095    93.444
4096    93.994
4097    93.444
4098    93.444
4099    93.444
4100    93.075
4101    93.918
4102    94.465
4103    93.994
4104    93.444
4105    93.918
4106    92.893
4107    93.444
4108    92.893
4109    92.431
4110    93.994
4111    94.055
4112    93.200
4113    93.200
4114    93.918
4115    93.918
4116    92.893
4117    93.444
4118    93.200
Name: cons.price.idx, Length: 4119, dtype: float64

In [91]:
bank.y.unique()

array(['no', 'yes', nan], dtype=object)

In [92]:
bank.age.unique()

array([ 30.,  39.,  25.,  38.,  47.,  32.,  41.,  31.,  35.,  36.,  29.,
        27.,  44.,  46.,  45.,  50.,  55.,  40.,  28.,  34.,  33.,  51.,
        48.,  nan,  20.,  76.,  56.,  24.,  58.,  60.,  37.,  52.,  42.,
        49.,  54.,  59.,  57.,  43.,  53.,  75.,  82.,  71.,  21.,  22.,
        23.,  26.,  81., 143., 250.,  61.,  67.,  73.,  18.,  64.,  74.,
        77.,  86.,  85.,  63.,  88.,  78.,  72.,  68.,  80.,  66.,  19.,
        62.,  65.,  69.,  70.])

In [93]:
bank=bank[(bank['age'] >=18) & (bank['age'] <=99) ]

In [94]:
bank.age.unique()

array([30., 39., 25., 38., 47., 32., 41., 31., 35., 36., 29., 27., 44.,
       46., 45., 50., 55., 40., 28., 34., 33., 51., 48., 20., 76., 56.,
       24., 58., 60., 37., 52., 42., 49., 54., 59., 57., 43., 53., 75.,
       82., 71., 21., 22., 23., 26., 81., 61., 67., 73., 18., 64., 74.,
       77., 86., 85., 63., 88., 78., 72., 68., 80., 66., 19., 62., 65.,
       69., 70.])

In [95]:
bank.dtypes

age               float64
job                object
marital            object
education          object
default            object
housing            object
loan               object
contact            object
month              object
day_of_week        object
duration          float64
campaign          float64
pdays             float64
previous          float64
poutcome           object
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
y                  object
dtype: object

In [96]:
bank.default.unique()

array(['no', 'unknown', 'yes'], dtype=object)

In [97]:
bank.housing.unique()

array(['yes', 'no', 'unknown'], dtype=object)

In [98]:
bank.loan.unique()

array(['no', 'unknown', 'yes'], dtype=object)

In [99]:
bank.contact.unique()

array(['cellular', 'telephone'], dtype=object)

In [100]:
 bank[['duration', 'y']][bank.duration == 0]

duration   y
1950       0.0  no

In [101]:
bank.pdays.unique()

array([999.,  12.,   3.,   6.,   5.,   2.,  10.,  11.,   7.,   1.,  18.,
         4.,  15.,   0.,  16.,   9.,  19.,  17.,  13.,  21.,  14.])

In [102]:
 bank.ix[~(bank['pdays']>0)]

C:\Users\jayar\Anaconda2\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


age       job   marital          education default housing loan  \
1046  48.0     admin   married  university.degree      no     yes  yes   
3127  44.0  services  divorced           basic.6y      no     yes   no   

       contact month day_of_week ...   campaign  pdays  previous  poutcome  \
1046  cellular   aug         wed ...        1.0    0.0       3.0   success   
3127  cellular   aug         wed ...        3.0    0.0       1.0   success   

     emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  nr.employed    y  
1046         -1.7          94.027          -38.3        0.9       4991.6  yes  
3127         -1.7          94.027          -38.3        0.9       4991.6  yes  

[2 rows x 21 columns]

In [103]:
bank.pdays.unique()

array([999.,  12.,   3.,   6.,   5.,   2.,  10.,  11.,   7.,   1.,  18.,
         4.,  15.,   0.,  16.,   9.,  19.,  17.,  13.,  21.,  14.])

In [104]:
bank=bank[(bank['pdays'] >0)  ]

In [105]:
bank.pdays.unique()

array([999.,  12.,   3.,   6.,   5.,   2.,  10.,  11.,   7.,   1.,  18.,
         4.,  15.,  16.,   9.,  19.,  17.,  13.,  21.,  14.])

In [106]:
bank.y.unique()

array(['no', 'yes', nan], dtype=object)

In [107]:
bank=bank[(bank['pdays'] >0)  ]

In [108]:
bank.dropna(axis =0,subset = ['y'], inplace=True)

In [109]:
bank.dropna(axis =0,subset =['poutcome'], inplace=True)

In [110]:
bank.dropna(axis =0,subset =['nr.employed'], inplace=True)

In [111]:
bank.y.unique()

array(['no', 'yes'], dtype=object)

In [112]:
bank['emp.var.rate'].fillna(bank['emp.var.rate'].mean(axis=0),inplace=True)

In [113]:
bank=bank[(bank['cons.price.idx'] <=100) & (bank['cons.price.idx'] >=80) ]

In [114]:
bank=bank[(bank['euribor3m'] >0)  ]

In [115]:
bank['euribor3m'].fillna(bank['euribor3m'].mean(axis=0),inplace=True)

In [116]:
t=bank['marital'].str.isspace()

In [117]:
bank.loc[2]

age                        25
job                  services
marital               married
education         high.school
default                    no
housing                   yes
loan                       no
contact             telephone
month                     jun
day_of_week               wed
duration                  227
campaign                    1
pdays                     999
previous                    0
poutcome          nonexistent
emp.var.rate              1.4
cons.price.idx         94.465
cons.conf.idx           -41.8
euribor3m               4.962
nr.employed            5228.1
y                          no
Name: 2, dtype: object

In [118]:
bank=bank[(bank['job'] !='unknown')  ]

In [119]:
words =['BANK','LOAN','MARITAL','EDuCatioN',]
list(map(str.lower, words))

['bank', 'loan', 'marital', 'education']

In [120]:
words =['BANK','LOAN','EDuCatioN','DefaULT']
list(map(str.upper, words))


['BANK', 'LOAN', 'EDUCATION', 'DEFAULT']

In [121]:
a="BANK"
result = a[:1] + a[1:].lower() 
print(result)

Bank


In [122]:
a="bank"
result = a[:1].upper() + a[1:]
print(result)

Bank


In [123]:
bank.to_csv('cleanedbank.csv', sep=';' , decimal='.')